---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.10
  - name: centos-7.7

verifier:
  name: inspec
  inspec_tests:
    - path: test/integration/default

suites:
  - name: default-12
    provisioner:
      product_name: chef
      product_version: 12
    run_list:
      - recipe[yum-hp::default]
      - recipe[yum-hp-test::default]
  - name: default-13
    provisioner:
      product_name: chef
      product_version: 13
    run_list:
      - recipe[yum-hp::default]
      - recipe[yum-hp-test::default]
  - name: default-14
    provisioner:
      product_name: chef
      product_version: 14
    run_list:
      - recipe[yum-hp::default]
      - recipe[yum-hp-test::default]
